
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pard = 26;
  public static final int menorigual = 15;
  public static final int tbool = 18;
  public static final int cadena = 22;
  public static final int decimal = 32;
  public static final int imprimir = 21;
  public static final int tint = 16;
  public static final int or = 6;
  public static final int caracter = 33;
  public static final int llaveI = 24;
  public static final int resta = 4;
  public static final int tchar = 17;
  public static final int tdouble = 20;
  public static final int menor = 13;
  public static final int llaveD = 25;
  public static final int tstring = 19;
  public static final int mayorigual = 14;
  public static final int div = 5;
  public static final int igual = 11;
  public static final int EOF = 0;
  public static final int verdadero = 30;
  public static final int desigual = 9;
  public static final int puntocoma = 23;
  public static final int negacion = 8;
  public static final int multi = 3;
  public static final int error = 1;
  public static final int entero = 31;
  public static final int suma = 2;
  public static final int falso = 29;
  public static final int pari = 27;
  public static final int igualigual = 10;
  public static final int and = 7;
  public static final int identificador = 28;
  public static final int mayor = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "suma",
  "multi",
  "resta",
  "div",
  "or",
  "and",
  "negacion",
  "desigual",
  "igualigual",
  "igual",
  "mayor",
  "menor",
  "mayorigual",
  "menorigual",
  "tint",
  "tchar",
  "tbool",
  "tstring",
  "tdouble",
  "imprimir",
  "cadena",
  "puntocoma",
  "llaveI",
  "llaveD",
  "pard",
  "pari",
  "identificador",
  "falso",
  "verdadero",
  "entero",
  "decimal",
  "caracter"
  };
}

